### ISSUE TITLE
Auto expanding by clicking inside content

### ISSUE THREAD

**Issue by mh2k9** [BrightspaceUI/more-less#15]
I have many `paper-checkbox` as content. When I click on any of that checkboxes then it expands automatically without clicking more link. How can I fix this problem?

**Comment by omsmith** [comment]
Hi @mh2k9 

Apologies for the late reply. The component auto expands largely in part to support keyboard users. If it didn't expand, you could tab inside the component and onto a focusable that is not visible on the page. Disabling this isn't something we'll plan to add.
