### ISSUE TITLE
Doesn't shrink when content shrinks

### ISSUE THREAD

**Issue by omsmith** [BrightspaceUI/more-less#21]
https://github.com/BrightspaceUI/more-less/blob/6129e8ce1c574e255e1d7be808e90c7e7257bfd4/d2l-more-less.html#L262

This `contentHeight` calculation is great for expanding - additional content being added means the content is taking up _more_ space than the container, and thus `scrollHeight > offsetHeight`. However once the content shrinks to be smaller than the container (text changes, and image is removed, whatever), `scrollHeight` will remain constant at `offsetHeight`, since we have a `height` property set.

```js
            var children = D2L.Dom.getComposedChildren(this.__contentSlot);
            var contentHeight = children.reduce(function (height, child) {
                return height + child.offsetHeight;
            }, 0);
```
Is close to working, but it doesn't account for margins and whatnot. Likely have to end up with removing the `height` property so it sizes with content, and grabbing the `offsetHeight`, but that's going to create visual jank.

Only reason for the `height` property is to be able to animate changes... might consider only animating actual expanding/collapsing by setting it JIT to `offsetHeight`, and then removing it, allowing it to adjust naturally as content changes.

**Comment by dlockhart** [comment]
This repo has moved to lit-core, and there is now code that checks for changes in content height. Feel free to re-open there if this is still an issue.
